package com.resale.homeflyappointment.model;

public enum ActionType {
    CUSTOMER_SCHEDULE_APPOINTMENT(1),
    CUSTOMER_AVAILABLE_APPOINTMENTS(2),
    GET_CUSTOMER_APPOINTMENTS(3),
    CUSTOMER_UPDATE_APPOINTMENT(4),
    CUSTOMER_RATE_APPOINTMENT(5),
    CUSTOMER_CANCEL_APPOINTMENT(6),
    GET_CUSTOMER_APPOINTMENT(7),
    IS_CUSTOMER_ON_CALL_INTERNAL(8),
    GET_CUSTOMER_ZOOM_DATA(9),
    IS_CUSTOMER_ON_CALL(10),
    CUSTOMER_GENERATE_OTP(11),
    CUSTOMER_VERIFY_OTP(12),
    IS_USER_ON_CALL_INTERNAL(13),
    INTERNAL_CREATE_APPOINTMENT_FROM_QUEUE(14),
    INTERNAL_END_CALL_FROM_QUEUE(15),
    INTERNAL_CHANGE_APPOINTMENT_STATUS_FROM_QUEUE(16),
    SEND_APPOINTMENT_TO_QUEUE(17),
    GET_APPOINTMENTS_BY_USER_ID(18),
    REASSIGN_APPOINTMENT(19),
    USER_GET_APPOINTMENTS(20),
    USER_CREATE_APPOINTMENT(21),
    USER_RESCHEDULE_APPOINTMENT(22),
    USER_CANCEL_APPOINTMENT(23),
    USER_CHANGE_APPOINTMENT_STATUS(24),
    USER_SEND_ZOOM_LINK(25),
    USER_GET_ZOOM_DATA(26),
    TEAM_LEAD_RESCHEDULE_APPOINTMENT(27),

    UNKNOWN(99); // fallback



    private final int code;

    ActionType(int code) {
        this.code = code;
    }

    public int getCode() {
        return code;
    }

}


